### ISSUE TITLE
Link to ERA repeated in owl:sameAs predicate for certain records (found in GraphDB canlink-test repository)

### ISSUE THREAD

**Issue by a-cohen** [ualbertalib/metadata#421] opened 2018-11-29 21:59 UTC
List of affected records:

- http://canlink.library.ualberta.ca/thesis/144ae1b01b0e2d88efb377f039c67463
- http://canlink.library.ualberta.ca/thesis/23085762b27d4af7beaf3997f9160ba2
- http://canlink.library.ualberta.ca/thesis/08d37776d89e19c97bc15494a0e847dd 
- http://canlink.library.ualberta.ca/thesis/1796d689b9ef627ad3fb16fff059900c
- http://canlink.library.ualberta.ca/thesis/381da719b352ffce90473d8f79924e82 
- http://canlink.library.ualberta.ca/thesis/504d20fb374a2f1296aa6afe1055ddc0
- http://canlink.library.ualberta.ca/thesis/51e78f8bc9c3e025196ee6b9fcd107cc
- http://canlink.library.ualberta.ca/thesis/55f2b7604de3b07bf03f01e7b7881fa3 
- http://canlink.library.ualberta.ca/thesis/56b3c98af8173f8c41990f9ed0c6efbe 
- http://canlink.library.ualberta.ca/thesis/62aff052d6cae09262628b1e67556503
- http://canlink.library.ualberta.ca/thesis/658dfa799a3aae34c071a5aea9f0cbff
- http://canlink.library.ualberta.ca/thesis/6c6904374e325ebf301d6f9042ccaef6
- http://canlink.library.ualberta.ca/thesis/6eecc1affa43ecabc170cc9d28ee3d1a
- http://canlink.library.ualberta.ca/thesis/6ef141c38cee2114789172969bb2a459
- http://canlink.library.ualberta.ca/thesis/6f31d5abf12ec82f68af238d38887868
- http://canlink.library.ualberta.ca/thesis/772d417d2e3efe1d056a86becd829a37
- http://canlink.library.ualberta.ca/thesis/77b55f5d380612dca67a721c0f2ecf3f
- http://canlink.library.ualberta.ca/thesis/80827b1030a2b2133561e7dc7433d43f
- http://canlink.library.ualberta.ca/thesis/8be64d409d2e5296bcf1ecc955142533
- http://canlink.library.ualberta.ca/thesis/9014f00b45a4a490c32d1e0fba8ecd73
- http://canlink.library.ualberta.ca/thesis/98b39cbf9c72e9ce2d4843181b32b566
- http://canlink.library.ualberta.ca/thesis/9f65ae7ea330df1a24d374ac16d14d6d
- http://canlink.library.ualberta.ca/thesis/a8b1f5a058d2760bb62bb9780ec689ba
- http://canlink.library.ualberta.ca/thesis/a9c1dc395e5f6ee92040272865d1473b
- http://canlink.library.ualberta.ca/thesis/b0397a7f7dd7ee7db0c37e84d7fefcc7
- http://canlink.library.ualberta.ca/thesis/b149c6b6c955b528e9a468b07a15e07c
- http://canlink.library.ualberta.ca/thesis/c145e7e703233d27b7158b6e9b72c2ee
- http://canlink.library.ualberta.ca/thesis/dc0e749e6ce47606ae6c767ad61024c5
- http://canlink.library.ualberta.ca/thesis/dcfe1bbaa5ad81745413c6f59d52397d
- http://canlink.library.ualberta.ca/thesis/e2261269c912bfd41706eb1bfaa9faae
- http://canlink.library.ualberta.ca/thesis/e3c2d70ff97fcc200d8e7c0a439d5c24
- http://canlink.library.ualberta.ca/thesis/fcc56049aa43888aa3389bbe1b37362b
- http://canlink.library.ualberta.ca/thesis/28b80f6d8e99aa73bb2456ace82f3943
- http://canlink.library.ualberta.ca/thesis/2ffcc5a26970579059b64ae86851c28f
- http://canlink.library.ualberta.ca/thesis/38922ac455afaf0fdf532ca800fd79b0
- http://canlink.library.ualberta.ca/thesis/554211322f0ccdb5829c8a2d8b380b51
- http://canlink.library.ualberta.ca/thesis/6c425f4277048f2e75d76bcbaa7e3ef4
- http://canlink.library.ualberta.ca/thesis/d73d9107cc47dd69d50e2e4d0dcb75f2
- http://canlink.library.ualberta.ca/thesis/d9f0aa8d92032f44c6268e3baa861790 

Screenshot example
![repeat](https://user-images.githubusercontent.com/45469510/49254604-db2d3200-f3e6-11e8-910d-30665ac23e85.PNG)

SPARQL query used to find this
```
select ?title ?link where {  
    ?thesis <http://purl.org/dc/terms/title> ?title .  
    ?thesis <http://www.w3.org/2002/07/owl#sameAs> ?link .
} limit 5008

```
@danydvd @anayram

**Comment by danydvd** [comment] 2018-11-30 16:36
Thank you @a-cohen. This is a problem with the origin sample data that was used in the CanLink [process](https://drive.google.com/open?id=0B-cFCxJCqDNTYzVlb3hfOWFGQTg). 
For example: [http://canlink.library.ualberta.ca/thesis/23085762b27d4af7beaf3997f9160ba2](http://canlink.library.ualberta.ca/thesis/23085762b27d4af7beaf3997f9160ba2) (hydraNoid: [ks65hd66n](https://drive.google.com/open?id=0B-3wsg6nRw9Td3BQNXhSWlgzQjA)) has this:
"<ns002:fedora3handle rdf:datatype="http://www.w3.org/2001/XMLSchema#string">http://hdl.handle.net/10402/era.27632http://hdl.handle.net/10402/era.27632</ns002:fedora3handle>"

This data seems to be fixed in the current ERA triplestore. I think a fresh pull of thesis and redo of the process would solve this.

**Comment by danydvd** [comment] 2019-06-24 17:14
The issue is resolved with the new data (e.g. http://206.167.181.124:8000/getitem/http://canlink.library.ualberta.ca/thesis/fcc56049aa43888aa3389bbe1b37362b)

**Closed by danydvd** 2019-06-24 17:14 UTC
Labels: CanLink
